# Generated by Django 2.1.5 on 2019-03-29 00:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url_type', models.SmallIntegerField(choices=[(0, 'absolute'), (1, 'dynamic')], default=0)),
                ('url_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='address',
            old_name='status',
            new_name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.SmallIntegerField(choices=[(0, 'Billing Address'), (1, 'Shipping Address')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.CustomerInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('name', 'url_name')},
        ),
        migrations.AddField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(to='repository.Menu'),
        ),
    ]
