# Generated by Django 2.1.5 on 2019-04-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20190405_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icons',
            field=models.TextField(),
        ),
    ]
