# Generated by Django 2.2.3 on 2019-07-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='repository.Category'),
        ),
    ]
