# Generated by Django 2.1.5 on 2019-04-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20190405_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
