# Generated by Django 2.1.5 on 2019-04-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_menu_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='icons',
            new_name='icon',
        ),
        migrations.AlterField(
            model_name='productlist',
            name='stock_level',
            field=models.FloatField(default=0),
        ),
    ]
