# Generated by Django 2.1.5 on 2019-05-25 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20190405_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thickness',
        ),
        migrations.RemoveField(
            model_name='product',
            name='veneer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.DeleteModel(
            name='ProductList',
        ),
    ]
