# Generated by Django 2.1.5 on 2019-05-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20190525_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
